### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by diggit** [iwasz/cpp-can-isotp#1]
Hi,
your library looks pretty good, but can't find any information about its' licensing. In such case is fully copyrighted to you and nobody else can benefit from it. Would you consider using some permissive license? (BSD/MIT/...)

**Comment by iwasz** [comment]
Hi, I've added MIT license in the README.md (at the end) and in a "COPYING" file. Sorry, I didn't get a notification about this issue. please reopen if further actions on my side are needed. Thanks.
